# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'exp_om.ui'
#
# Created: Fri Oct 16 10:34:41 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(649, 543)
        self.tabMain = QtGui.QTabWidget(Dialog)
        self.tabMain.setGeometry(QtCore.QRect(10, 10, 631, 481))
        self.tabMain.setTabPosition(QtGui.QTabWidget.North)
        self.tabMain.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabMain.setObjectName(_fromUtf8("tabMain"))
        self.tabDades = QtGui.QWidget()
        self.tabDades.setObjectName(_fromUtf8("tabDades"))
        self.gb1Expedient = QtGui.QGroupBox(self.tabDades)
        self.gb1Expedient.setGeometry(QtCore.QRect(10, 10, 601, 141))
        self.gb1Expedient.setObjectName(_fromUtf8("gb1Expedient"))
        self.lblNumExp = QtGui.QLabel(self.gb1Expedient)
        self.lblNumExp.setGeometry(QtCore.QRect(430, 20, 51, 20))
        self.lblNumExp.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblNumExp.setObjectName(_fromUtf8("lblNumExp"))
        self.txtNumExp = QtGui.QLineEdit(self.gb1Expedient)
        self.txtNumExp.setEnabled(True)
        self.txtNumExp.setGeometry(QtCore.QRect(510, 20, 81, 20))
        self.txtNumExp.setMaxLength(6)
        self.txtNumExp.setObjectName(_fromUtf8("txtNumExp"))
        self.lblTip = QtGui.QLabel(self.gb1Expedient)
        self.lblTip.setGeometry(QtCore.QRect(10, 50, 71, 21))
        self.lblTip.setObjectName(_fromUtf8("lblTip"))
        self.cboTipus = QtGui.QComboBox(self.gb1Expedient)
        self.cboTipus.setGeometry(QtCore.QRect(100, 50, 301, 22))
        self.cboTipus.setEditable(True)
        self.cboTipus.setMaxVisibleItems(20)
        self.cboTipus.setObjectName(_fromUtf8("cboTipus"))
        self.txtNumHab = QtGui.QLineEdit(self.gb1Expedient)
        self.txtNumHab.setGeometry(QtCore.QRect(510, 50, 81, 20))
        self.txtNumHab.setMaxLength(4)
        self.txtNumHab.setObjectName(_fromUtf8("txtNumHab"))
        self.lblHab = QtGui.QLabel(self.gb1Expedient)
        self.lblHab.setGeometry(QtCore.QRect(430, 50, 66, 21))
        self.lblHab.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblHab.setObjectName(_fromUtf8("lblHab"))
        self.lblDataLlicencia = QtGui.QLabel(self.gb1Expedient)
        self.lblDataLlicencia.setGeometry(QtCore.QRect(430, 80, 76, 21))
        self.lblDataLlicencia.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblDataLlicencia.setObjectName(_fromUtf8("lblDataLlicencia"))
        self.dateLlicencia = QtGui.QDateEdit(self.gb1Expedient)
        self.dateLlicencia.setGeometry(QtCore.QRect(510, 80, 81, 22))
        self.dateLlicencia.setDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateLlicencia.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateLlicencia.setMaximumDate(QtCore.QDate(2099, 12, 31))
        self.dateLlicencia.setCalendarPopup(True)
        self.dateLlicencia.setObjectName(_fromUtf8("dateLlicencia"))
        self.txtId = QtGui.QLineEdit(self.gb1Expedient)
        self.txtId.setEnabled(False)
        self.txtId.setGeometry(QtCore.QRect(100, 20, 81, 20))
        self.txtId.setMaxLength(5)
        self.txtId.setObjectName(_fromUtf8("txtId"))
        self.dateEntrada = QtGui.QDateEdit(self.gb1Expedient)
        self.dateEntrada.setGeometry(QtCore.QRect(320, 80, 81, 22))
        self.dateEntrada.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateEntrada.setMaximumDate(QtCore.QDate(2099, 12, 31))
        self.dateEntrada.setCalendarPopup(True)
        self.dateEntrada.setObjectName(_fromUtf8("dateEntrada"))
        self.lblDataEntrada = QtGui.QLabel(self.gb1Expedient)
        self.lblDataEntrada.setGeometry(QtCore.QRect(220, 80, 101, 21))
        self.lblDataEntrada.setObjectName(_fromUtf8("lblDataEntrada"))
        self.lblId = QtGui.QLabel(self.gb1Expedient)
        self.lblId.setGeometry(QtCore.QRect(10, 20, 91, 21))
        self.lblId.setObjectName(_fromUtf8("lblId"))
        self.dateLiquidacio = QtGui.QDateEdit(self.gb1Expedient)
        self.dateLiquidacio.setGeometry(QtCore.QRect(320, 20, 81, 22))
        self.dateLiquidacio.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateLiquidacio.setMaximumDate(QtCore.QDate(2099, 12, 31))
        self.dateLiquidacio.setCalendarPopup(True)
        self.dateLiquidacio.setObjectName(_fromUtf8("dateLiquidacio"))
        self.lblDataLiquidacio = QtGui.QLabel(self.gb1Expedient)
        self.lblDataLiquidacio.setGeometry(QtCore.QRect(220, 20, 101, 21))
        self.lblDataLiquidacio.setObjectName(_fromUtf8("lblDataLiquidacio"))
        self.lblEntrada = QtGui.QLabel(self.gb1Expedient)
        self.lblEntrada.setGeometry(QtCore.QRect(10, 80, 81, 21))
        self.lblEntrada.setObjectName(_fromUtf8("lblEntrada"))
        self.txtRegEnt = QtGui.QLineEdit(self.gb1Expedient)
        self.txtRegEnt.setGeometry(QtCore.QRect(100, 80, 81, 20))
        self.txtRegEnt.setMaxLength(5)
        self.txtRegEnt.setObjectName(_fromUtf8("txtRegEnt"))
        self.btnGenExp = QtGui.QPushButton(self.gb1Expedient)
        self.btnGenExp.setGeometry(QtCore.QRect(510, 110, 81, 23))
        self.btnGenExp.setIconSize(QtCore.QSize(24, 24))
        self.btnGenExp.setObjectName(_fromUtf8("btnGenExp"))
        self.gb2Interessat = QtGui.QGroupBox(self.tabDades)
        self.gb2Interessat.setGeometry(QtCore.QRect(10, 160, 601, 171))
        self.gb2Interessat.setObjectName(_fromUtf8("gb2Interessat"))
        self.lblSol = QtGui.QLabel(self.gb2Interessat)
        self.lblSol.setGeometry(QtCore.QRect(10, 50, 101, 21))
        self.lblSol.setObjectName(_fromUtf8("lblSol"))
        self.lblRep = QtGui.QLabel(self.gb2Interessat)
        self.lblRep.setGeometry(QtCore.QRect(10, 80, 101, 21))
        self.lblRep.setObjectName(_fromUtf8("lblRep"))
        self.lblAdre = QtGui.QLabel(self.gb2Interessat)
        self.lblAdre.setGeometry(QtCore.QRect(10, 110, 101, 21))
        self.lblAdre.setObjectName(_fromUtf8("lblAdre"))
        self.txtNotifAdreca = QtGui.QLineEdit(self.gb2Interessat)
        self.txtNotifAdreca.setGeometry(QtCore.QRect(110, 110, 351, 20))
        self.txtNotifAdreca.setText(_fromUtf8(""))
        self.txtNotifAdreca.setMaxLength(100)
        self.txtNotifAdreca.setObjectName(_fromUtf8("txtNotifAdreca"))
        self.lblCp = QtGui.QLabel(self.gb2Interessat)
        self.lblCp.setGeometry(QtCore.QRect(10, 140, 91, 21))
        self.lblCp.setObjectName(_fromUtf8("lblCp"))
        self.txtNotifCp = QtGui.QLineEdit(self.gb2Interessat)
        self.txtNotifCp.setGeometry(QtCore.QRect(110, 140, 111, 20))
        self.txtNotifCp.setText(_fromUtf8(""))
        self.txtNotifCp.setMaxLength(5)
        self.txtNotifCp.setObjectName(_fromUtf8("txtNotifCp"))
        self.btnJuridica = QtGui.QPushButton(self.gb2Interessat)
        self.btnJuridica.setGeometry(QtCore.QRect(480, 110, 111, 23))
        self.btnJuridica.setObjectName(_fromUtf8("btnJuridica"))
        self.btnFisica = QtGui.QPushButton(self.gb2Interessat)
        self.btnFisica.setGeometry(QtCore.QRect(480, 140, 111, 23))
        self.btnFisica.setObjectName(_fromUtf8("btnFisica"))
        self.txtSolDades = QtGui.QLineEdit(self.gb2Interessat)
        self.txtSolDades.setEnabled(False)
        self.txtSolDades.setGeometry(QtCore.QRect(240, 50, 351, 20))
        self.txtSolDades.setMaxLength(15)
        self.txtSolDades.setObjectName(_fromUtf8("txtSolDades"))
        self.txtRepDades = QtGui.QLineEdit(self.gb2Interessat)
        self.txtRepDades.setEnabled(False)
        self.txtRepDades.setGeometry(QtCore.QRect(240, 80, 351, 20))
        self.txtRepDades.setMaxLength(15)
        self.txtRepDades.setObjectName(_fromUtf8("txtRepDades"))
        self.txtNotifPoblacio = QtGui.QLineEdit(self.gb2Interessat)
        self.txtNotifPoblacio.setGeometry(QtCore.QRect(240, 140, 221, 20))
        self.txtNotifPoblacio.setText(_fromUtf8(""))
        self.txtNotifPoblacio.setMaxLength(100)
        self.txtNotifPoblacio.setObjectName(_fromUtf8("txtNotifPoblacio"))
        self.cboSol = QtGui.QComboBox(self.gb2Interessat)
        self.cboSol.setGeometry(QtCore.QRect(110, 50, 111, 22))
        self.cboSol.setEditable(True)
        self.cboSol.setObjectName(_fromUtf8("cboSol"))
        self.rbFisica = QtGui.QRadioButton(self.gb2Interessat)
        self.rbFisica.setGeometry(QtCore.QRect(110, 20, 61, 21))
        self.rbFisica.setChecked(True)
        self.rbFisica.setObjectName(_fromUtf8("rbFisica"))
        self.rbJuridica = QtGui.QRadioButton(self.gb2Interessat)
        self.rbJuridica.setGeometry(QtCore.QRect(190, 20, 82, 21))
        self.rbJuridica.setObjectName(_fromUtf8("rbJuridica"))
        self.lblSol_2 = QtGui.QLabel(self.gb2Interessat)
        self.lblSol_2.setGeometry(QtCore.QRect(10, 20, 81, 21))
        self.lblSol_2.setObjectName(_fromUtf8("lblSol_2"))
        self.cboRep = QtGui.QComboBox(self.gb2Interessat)
        self.cboRep.setGeometry(QtCore.QRect(110, 80, 111, 22))
        self.cboRep.setEditable(True)
        self.cboRep.setObjectName(_fromUtf8("cboRep"))
        self.cboSolCif = QtGui.QComboBox(self.gb2Interessat)
        self.cboSolCif.setGeometry(QtCore.QRect(110, 50, 111, 22))
        self.cboSolCif.setEditable(True)
        self.cboSolCif.setObjectName(_fromUtf8("cboSolCif"))
        self.gb3Emplasament = QtGui.QGroupBox(self.tabDades)
        self.gb3Emplasament.setGeometry(QtCore.QRect(10, 340, 601, 81))
        self.gb3Emplasament.setFlat(False)
        self.gb3Emplasament.setCheckable(False)
        self.gb3Emplasament.setObjectName(_fromUtf8("gb3Emplasament"))
        self.refcat = QtGui.QLineEdit(self.gb3Emplasament)
        self.refcat.setEnabled(False)
        self.refcat.setGeometry(QtCore.QRect(110, 20, 141, 20))
        self.refcat.setMaxLength(14)
        self.refcat.setObjectName(_fromUtf8("refcat"))
        self.lblRefcat20 = QtGui.QLabel(self.gb3Emplasament)
        self.lblRefcat20.setGeometry(QtCore.QRect(280, 20, 81, 21))
        self.lblRefcat20.setObjectName(_fromUtf8("lblRefcat20"))
        self.lblEmpl = QtGui.QLabel(self.gb3Emplasament)
        self.lblEmpl.setGeometry(QtCore.QRect(10, 50, 91, 21))
        self.lblEmpl.setObjectName(_fromUtf8("lblEmpl"))
        self.txtRefcat20 = QtGui.QLineEdit(self.gb3Emplasament)
        self.txtRefcat20.setEnabled(False)
        self.txtRefcat20.setGeometry(QtCore.QRect(370, 20, 141, 20))
        self.txtRefcat20.setMaxLength(25)
        self.txtRefcat20.setObjectName(_fromUtf8("txtRefcat20"))
        self.cboEmp = QtGui.QComboBox(self.gb3Emplasament)
        self.cboEmp.setGeometry(QtCore.QRect(110, 50, 401, 22))
        self.cboEmp.setEditable(True)
        self.cboEmp.setObjectName(_fromUtf8("cboEmp"))
        self.lblRef_2 = QtGui.QLabel(self.gb3Emplasament)
        self.lblRef_2.setGeometry(QtCore.QRect(10, 20, 81, 21))
        self.lblRef_2.setObjectName(_fromUtf8("lblRef_2"))
        self.tabMain.addTab(self.tabDades, _fromUtf8(""))
        self.tabLiquidacio = QtGui.QWidget()
        self.tabLiquidacio.setObjectName(_fromUtf8("tabLiquidacio"))
        self.txtPress = QtGui.QLineEdit(self.tabLiquidacio)
        self.txtPress.setGeometry(QtCore.QRect(110, 20, 101, 20))
        self.txtPress.setText(_fromUtf8(""))
        self.txtPress.setMaxLength(15)
        self.txtPress.setObjectName(_fromUtf8("txtPress"))
        self.gb5 = QtGui.QGroupBox(self.tabLiquidacio)
        self.gb5.setGeometry(QtCore.QRect(230, 10, 381, 61))
        self.gb5.setObjectName(_fromUtf8("gb5"))
        self.lblIcio = QtGui.QLabel(self.gb5)
        self.lblIcio.setGeometry(QtCore.QRect(10, 30, 41, 21))
        self.lblIcio.setObjectName(_fromUtf8("lblIcio"))
        self.txtPlaca = QtGui.QLineEdit(self.gb5)
        self.txtPlaca.setEnabled(False)
        self.txtPlaca.setGeometry(QtCore.QRect(320, 30, 51, 20))
        self.txtPlaca.setText(_fromUtf8(""))
        self.txtPlaca.setMaxLength(15)
        self.txtPlaca.setObjectName(_fromUtf8("txtPlaca"))
        self.chkPlaca = QtGui.QCheckBox(self.gb5)
        self.chkPlaca.setGeometry(QtCore.QRect(260, 30, 51, 21))
        self.chkPlaca.setObjectName(_fromUtf8("chkPlaca"))
        self.txtIcio = QtGui.QLineEdit(self.gb5)
        self.txtIcio.setEnabled(False)
        self.txtIcio.setGeometry(QtCore.QRect(40, 30, 71, 20))
        self.txtIcio.setText(_fromUtf8(""))
        self.txtIcio.setMaxLength(15)
        self.txtIcio.setObjectName(_fromUtf8("txtIcio"))
        self.chkBonIcio = QtGui.QCheckBox(self.gb5)
        self.chkBonIcio.setGeometry(QtCore.QRect(130, 30, 101, 21))
        self.chkBonIcio.setObjectName(_fromUtf8("chkBonIcio"))
        self.gbUrb = QtGui.QGroupBox(self.tabLiquidacio)
        self.gbUrb.setGeometry(QtCore.QRect(10, 90, 331, 331))
        self.gbUrb.setObjectName(_fromUtf8("gbUrb"))
        self.txtPlu = QtGui.QLineEdit(self.gbUrb)
        self.txtPlu.setEnabled(False)
        self.txtPlu.setGeometry(QtCore.QRect(100, 20, 61, 20))
        self.txtPlu.setText(_fromUtf8(""))
        self.txtPlu.setMaxLength(15)
        self.txtPlu.setObjectName(_fromUtf8("txtPlu"))
        self.txtEnd = QtGui.QLineEdit(self.gbUrb)
        self.txtEnd.setEnabled(False)
        self.txtEnd.setGeometry(QtCore.QRect(230, 50, 91, 20))
        self.txtEnd.setText(_fromUtf8(""))
        self.txtEnd.setMaxLength(15)
        self.txtEnd.setObjectName(_fromUtf8("txtEnd"))
        self.txtMov = QtGui.QLineEdit(self.gbUrb)
        self.txtMov.setEnabled(False)
        self.txtMov.setGeometry(QtCore.QRect(230, 110, 91, 20))
        self.txtMov.setText(_fromUtf8(""))
        self.txtMov.setMaxLength(15)
        self.txtMov.setObjectName(_fromUtf8("txtMov"))
        self.txtFig = QtGui.QLineEdit(self.gbUrb)
        self.txtFig.setEnabled(False)
        self.txtFig.setGeometry(QtCore.QRect(230, 140, 91, 20))
        self.txtFig.setText(_fromUtf8(""))
        self.txtFig.setMaxLength(15)
        self.txtFig.setObjectName(_fromUtf8("txtFig"))
        self.txtPro = QtGui.QLineEdit(self.gbUrb)
        self.txtPro.setEnabled(False)
        self.txtPro.setGeometry(QtCore.QRect(230, 230, 91, 20))
        self.txtPro.setText(_fromUtf8(""))
        self.txtPro.setMaxLength(15)
        self.txtPro.setObjectName(_fromUtf8("txtPro"))
        self.txtPar = QtGui.QLineEdit(self.gbUrb)
        self.txtPar.setEnabled(False)
        self.txtPar.setGeometry(QtCore.QRect(230, 200, 91, 20))
        self.txtPar.setText(_fromUtf8(""))
        self.txtPar.setMaxLength(15)
        self.txtPar.setObjectName(_fromUtf8("txtPar"))
        self.txtLeg = QtGui.QLineEdit(self.gbUrb)
        self.txtLeg.setEnabled(False)
        self.txtLeg.setGeometry(QtCore.QRect(230, 170, 91, 20))
        self.txtLeg.setText(_fromUtf8(""))
        self.txtLeg.setMaxLength(15)
        self.txtLeg.setObjectName(_fromUtf8("txtLeg"))
        self.chkEnd = QtGui.QCheckBox(self.gbUrb)
        self.chkEnd.setGeometry(QtCore.QRect(10, 50, 81, 21))
        self.chkEnd.setObjectName(_fromUtf8("chkEnd"))
        self.chkMov = QtGui.QCheckBox(self.gbUrb)
        self.chkMov.setGeometry(QtCore.QRect(10, 110, 121, 21))
        self.chkMov.setObjectName(_fromUtf8("chkMov"))
        self.chkLeg = QtGui.QCheckBox(self.gbUrb)
        self.chkLeg.setGeometry(QtCore.QRect(10, 170, 81, 21))
        self.chkLeg.setObjectName(_fromUtf8("chkLeg"))
        self.chkPar = QtGui.QCheckBox(self.gbUrb)
        self.chkPar.setGeometry(QtCore.QRect(10, 200, 81, 21))
        self.chkPar.setObjectName(_fromUtf8("chkPar"))
        self.chkPro = QtGui.QCheckBox(self.gbUrb)
        self.chkPro.setGeometry(QtCore.QRect(10, 230, 81, 21))
        self.chkPro.setObjectName(_fromUtf8("chkPro"))
        self.chkPlu = QtGui.QCheckBox(self.gbUrb)
        self.chkPlu.setGeometry(QtCore.QRect(10, 20, 81, 21))
        self.chkPlu.setObjectName(_fromUtf8("chkPlu"))
        self.chkRes = QtGui.QCheckBox(self.gbUrb)
        self.chkRes.setGeometry(QtCore.QRect(170, 20, 81, 21))
        self.chkRes.setObjectName(_fromUtf8("chkRes"))
        self.chkFig = QtGui.QCheckBox(self.gbUrb)
        self.chkFig.setGeometry(QtCore.QRect(10, 140, 121, 21))
        self.chkFig.setObjectName(_fromUtf8("chkFig"))
        self.txtRes = QtGui.QLineEdit(self.gbUrb)
        self.txtRes.setEnabled(False)
        self.txtRes.setGeometry(QtCore.QRect(260, 20, 61, 20))
        self.txtRes.setText(_fromUtf8(""))
        self.txtRes.setMaxLength(15)
        self.txtRes.setObjectName(_fromUtf8("txtRes"))
        self.txtCar = QtGui.QLineEdit(self.gbUrb)
        self.txtCar.setEnabled(False)
        self.txtCar.setGeometry(QtCore.QRect(230, 80, 91, 20))
        self.txtCar.setText(_fromUtf8(""))
        self.txtCar.setMaxLength(15)
        self.txtCar.setObjectName(_fromUtf8("txtCar"))
        self.chkCar = QtGui.QCheckBox(self.gbUrb)
        self.chkCar.setGeometry(QtCore.QRect(10, 80, 81, 21))
        self.chkCar.setObjectName(_fromUtf8("chkCar"))
        self.txtCarM = QtGui.QLineEdit(self.gbUrb)
        self.txtCarM.setGeometry(QtCore.QRect(130, 80, 61, 20))
        self.txtCarM.setText(_fromUtf8(""))
        self.txtCarM.setMaxLength(10)
        self.txtCarM.setObjectName(_fromUtf8("txtCarM"))
        self.lblNumExp_86 = QtGui.QLabel(self.gbUrb)
        self.lblNumExp_86.setGeometry(QtCore.QRect(200, 80, 21, 21))
        self.lblNumExp_86.setObjectName(_fromUtf8("lblNumExp_86"))
        self.lblNumExp_97 = QtGui.QLabel(self.gbUrb)
        self.lblNumExp_97.setGeometry(QtCore.QRect(200, 200, 21, 21))
        self.lblNumExp_97.setObjectName(_fromUtf8("lblNumExp_97"))
        self.txtParM = QtGui.QLineEdit(self.gbUrb)
        self.txtParM.setGeometry(QtCore.QRect(130, 200, 61, 20))
        self.txtParM.setText(_fromUtf8(""))
        self.txtParM.setMaxLength(10)
        self.txtParM.setObjectName(_fromUtf8("txtParM"))
        self.txtFigM = QtGui.QLineEdit(self.gbUrb)
        self.txtFigM.setGeometry(QtCore.QRect(130, 140, 61, 20))
        self.txtFigM.setText(_fromUtf8(""))
        self.txtFigM.setMaxLength(10)
        self.txtFigM.setObjectName(_fromUtf8("txtFigM"))
        self.lblNumExp_98 = QtGui.QLabel(self.gbUrb)
        self.lblNumExp_98.setGeometry(QtCore.QRect(200, 140, 21, 21))
        self.lblNumExp_98.setObjectName(_fromUtf8("lblNumExp_98"))
        self.lblNumExp_99 = QtGui.QLabel(self.gbUrb)
        self.lblNumExp_99.setGeometry(QtCore.QRect(200, 110, 21, 21))
        self.lblNumExp_99.setObjectName(_fromUtf8("lblNumExp_99"))
        self.txtMovM = QtGui.QLineEdit(self.gbUrb)
        self.txtMovM.setGeometry(QtCore.QRect(130, 110, 61, 20))
        self.txtMovM.setText(_fromUtf8(""))
        self.txtMovM.setMaxLength(10)
        self.txtMovM.setObjectName(_fromUtf8("txtMovM"))
        self.txtLlicTot = QtGui.QLineEdit(self.gbUrb)
        self.txtLlicTot.setEnabled(False)
        self.txtLlicTot.setGeometry(QtCore.QRect(230, 270, 91, 20))
        self.txtLlicTot.setText(_fromUtf8(""))
        self.txtLlicTot.setMaxLength(15)
        self.txtLlicTot.setObjectName(_fromUtf8("txtLlicTot"))
        self.lblTot_2 = QtGui.QLabel(self.gbUrb)
        self.lblTot_2.setGeometry(QtCore.QRect(70, 270, 151, 21))
        self.lblTot_2.setObjectName(_fromUtf8("lblTot_2"))
        self.chkBonLlic = QtGui.QCheckBox(self.gbUrb)
        self.chkBonLlic.setGeometry(QtCore.QRect(70, 300, 191, 21))
        self.chkBonLlic.setObjectName(_fromUtf8("chkBonLlic"))
        self.gbClav = QtGui.QGroupBox(self.tabLiquidacio)
        self.gbClav.setGeometry(QtCore.QRect(350, 90, 261, 151))
        self.gbClav.setObjectName(_fromUtf8("gbClav"))
        self.txtClavUni = QtGui.QLineEdit(self.gbClav)
        self.txtClavUni.setEnabled(False)
        self.txtClavUni.setGeometry(QtCore.QRect(180, 20, 71, 20))
        self.txtClavUni.setText(_fromUtf8(""))
        self.txtClavUni.setMaxLength(15)
        self.txtClavUni.setObjectName(_fromUtf8("txtClavUni"))
        self.nif_solic_75 = QtGui.QLineEdit(self.gbClav)
        self.nif_solic_75.setGeometry(QtCore.QRect(270, 20, 51, 20))
        self.nif_solic_75.setText(_fromUtf8(""))
        self.nif_solic_75.setMaxLength(15)
        self.nif_solic_75.setObjectName(_fromUtf8("nif_solic_75"))
        self.chkClavUni = QtGui.QCheckBox(self.gbClav)
        self.chkClavUni.setGeometry(QtCore.QRect(10, 20, 81, 21))
        self.chkClavUni.setObjectName(_fromUtf8("chkClavUni"))
        self.chkClavPlu = QtGui.QCheckBox(self.gbClav)
        self.chkClavPlu.setGeometry(QtCore.QRect(10, 50, 91, 21))
        self.chkClavPlu.setObjectName(_fromUtf8("chkClavPlu"))
        self.cboClavPlu = QtGui.QComboBox(self.gbClav)
        self.cboClavPlu.setGeometry(QtCore.QRect(110, 50, 61, 22))
        self.cboClavPlu.setObjectName(_fromUtf8("cboClavPlu"))
        self.txtClavMes = QtGui.QLineEdit(self.gbClav)
        self.txtClavMes.setEnabled(False)
        self.txtClavMes.setGeometry(QtCore.QRect(180, 80, 71, 20))
        self.txtClavMes.setText(_fromUtf8(""))
        self.txtClavMes.setMaxLength(15)
        self.txtClavMes.setObjectName(_fromUtf8("txtClavMes"))
        self.chkClavMes = QtGui.QCheckBox(self.gbClav)
        self.chkClavMes.setGeometry(QtCore.QRect(10, 80, 111, 21))
        self.chkClavMes.setObjectName(_fromUtf8("chkClavMes"))
        self.lblNumExp_79 = QtGui.QLabel(self.gbClav)
        self.lblNumExp_79.setGeometry(QtCore.QRect(-250, 400, 111, 16))
        self.lblNumExp_79.setObjectName(_fromUtf8("lblNumExp_79"))
        self.nif_solic_24 = QtGui.QLineEdit(self.gbClav)
        self.nif_solic_24.setGeometry(QtCore.QRect(-140, 400, 113, 20))
        self.nif_solic_24.setText(_fromUtf8(""))
        self.nif_solic_24.setMaxLength(15)
        self.nif_solic_24.setObjectName(_fromUtf8("nif_solic_24"))
        self.txtClavTot = QtGui.QLineEdit(self.gbClav)
        self.txtClavTot.setEnabled(False)
        self.txtClavTot.setGeometry(QtCore.QRect(162, 120, 91, 20))
        self.txtClavTot.setText(_fromUtf8(""))
        self.txtClavTot.setMaxLength(15)
        self.txtClavTot.setObjectName(_fromUtf8("txtClavTot"))
        self.lblTot_3 = QtGui.QLabel(self.gbClav)
        self.lblTot_3.setGeometry(QtCore.QRect(40, 120, 101, 21))
        self.lblTot_3.setObjectName(_fromUtf8("lblTot_3"))
        self.nif_solic_36 = QtGui.QLineEdit(self.gbClav)
        self.nif_solic_36.setGeometry(QtCore.QRect(320, 240, 113, 20))
        self.nif_solic_36.setText(_fromUtf8(""))
        self.nif_solic_36.setMaxLength(15)
        self.nif_solic_36.setObjectName(_fromUtf8("nif_solic_36"))
        self.lblNumExp_82 = QtGui.QLabel(self.gbClav)
        self.lblNumExp_82.setGeometry(QtCore.QRect(220, 240, 111, 16))
        self.lblNumExp_82.setObjectName(_fromUtf8("lblNumExp_82"))
        self.txtClavPlu = QtGui.QLineEdit(self.gbClav)
        self.txtClavPlu.setEnabled(False)
        self.txtClavPlu.setGeometry(QtCore.QRect(180, 50, 71, 20))
        self.txtClavPlu.setText(_fromUtf8(""))
        self.txtClavPlu.setMaxLength(15)
        self.txtClavPlu.setObjectName(_fromUtf8("txtClavPlu"))
        self.txtClavMesN = QtGui.QLineEdit(self.gbClav)
        self.txtClavMesN.setGeometry(QtCore.QRect(110, 80, 61, 20))
        self.txtClavMesN.setText(_fromUtf8(""))
        self.txtClavMesN.setMaxLength(5)
        self.txtClavMesN.setObjectName(_fromUtf8("txtClavMesN"))
        self.txtClavUniN = QtGui.QLineEdit(self.gbClav)
        self.txtClavUniN.setGeometry(QtCore.QRect(110, 20, 61, 20))
        self.txtClavUniN.setText(_fromUtf8(""))
        self.txtClavUniN.setMaxLength(5)
        self.txtClavUniN.setObjectName(_fromUtf8("txtClavUniN"))
        self.gbTot = QtGui.QGroupBox(self.tabLiquidacio)
        self.gbTot.setGeometry(QtCore.QRect(350, 250, 261, 81))
        self.gbTot.setObjectName(_fromUtf8("gbTot"))
        self.nif_solic_79 = QtGui.QLineEdit(self.gbTot)
        self.nif_solic_79.setGeometry(QtCore.QRect(270, 20, 51, 20))
        self.nif_solic_79.setText(_fromUtf8(""))
        self.nif_solic_79.setMaxLength(15)
        self.nif_solic_79.setObjectName(_fromUtf8("nif_solic_79"))
        self.lblNumExp_84 = QtGui.QLabel(self.gbTot)
        self.lblNumExp_84.setGeometry(QtCore.QRect(-250, 400, 111, 16))
        self.lblNumExp_84.setObjectName(_fromUtf8("lblNumExp_84"))
        self.nif_solic_25 = QtGui.QLineEdit(self.gbTot)
        self.nif_solic_25.setGeometry(QtCore.QRect(-140, 400, 113, 20))
        self.nif_solic_25.setText(_fromUtf8(""))
        self.nif_solic_25.setMaxLength(15)
        self.nif_solic_25.setObjectName(_fromUtf8("nif_solic_25"))
        self.nif_solic_39 = QtGui.QLineEdit(self.gbTot)
        self.nif_solic_39.setGeometry(QtCore.QRect(320, 240, 113, 20))
        self.nif_solic_39.setText(_fromUtf8(""))
        self.nif_solic_39.setMaxLength(15)
        self.nif_solic_39.setObjectName(_fromUtf8("nif_solic_39"))
        self.lblNumExp_87 = QtGui.QLabel(self.gbTot)
        self.lblNumExp_87.setGeometry(QtCore.QRect(220, 240, 111, 16))
        self.lblNumExp_87.setObjectName(_fromUtf8("lblNumExp_87"))
        self.txtTotalLiq = QtGui.QLineEdit(self.gbTot)
        self.txtTotalLiq.setEnabled(False)
        self.txtTotalLiq.setGeometry(QtCore.QRect(160, 20, 91, 20))
        self.txtTotalLiq.setText(_fromUtf8(""))
        self.txtTotalLiq.setMaxLength(15)
        self.txtTotalLiq.setObjectName(_fromUtf8("txtTotalLiq"))
        self.lblTotLiq = QtGui.QLabel(self.gbTot)
        self.lblTotLiq.setGeometry(QtCore.QRect(40, 20, 81, 21))
        self.lblTotLiq.setObjectName(_fromUtf8("lblTotLiq"))
        self.txtTotalLiq_2 = QtGui.QLineEdit(self.gbTot)
        self.txtTotalLiq_2.setEnabled(False)
        self.txtTotalLiq_2.setGeometry(QtCore.QRect(160, 50, 91, 20))
        self.txtTotalLiq_2.setText(_fromUtf8(""))
        self.txtTotalLiq_2.setMaxLength(15)
        self.txtTotalLiq_2.setObjectName(_fromUtf8("txtTotalLiq_2"))
        self.lblTotLiq_2 = QtGui.QLabel(self.gbTot)
        self.lblTotLiq_2.setGeometry(QtCore.QRect(40, 50, 101, 21))
        self.lblTotLiq_2.setObjectName(_fromUtf8("lblTotLiq_2"))
        self.txtLiqAj = QtGui.QLineEdit(self.tabLiquidacio)
        self.txtLiqAj.setGeometry(QtCore.QRect(110, 50, 101, 20))
        self.txtLiqAj.setText(_fromUtf8(""))
        self.txtLiqAj.setMaxLength(15)
        self.txtLiqAj.setObjectName(_fromUtf8("txtLiqAj"))
        self.chkLiqAj = QtGui.QCheckBox(self.tabLiquidacio)
        self.chkLiqAj.setGeometry(QtCore.QRect(20, 50, 81, 21))
        self.chkLiqAj.setObjectName(_fromUtf8("chkLiqAj"))
        self.gbGar = QtGui.QGroupBox(self.tabLiquidacio)
        self.gbGar.setGeometry(QtCore.QRect(350, 340, 261, 81))
        self.gbGar.setObjectName(_fromUtf8("gbGar"))
        self.txtGarRes = QtGui.QLineEdit(self.gbGar)
        self.txtGarRes.setEnabled(False)
        self.txtGarRes.setGeometry(QtCore.QRect(162, 20, 91, 20))
        self.txtGarRes.setText(_fromUtf8(""))
        self.txtGarRes.setMaxLength(15)
        self.txtGarRes.setObjectName(_fromUtf8("txtGarRes"))
        self.chkGarRes = QtGui.QCheckBox(self.gbGar)
        self.chkGarRes.setGeometry(QtCore.QRect(10, 20, 81, 21))
        self.chkGarRes.setObjectName(_fromUtf8("chkGarRes"))
        self.txtGarSer = QtGui.QLineEdit(self.gbGar)
        self.txtGarSer.setEnabled(False)
        self.txtGarSer.setGeometry(QtCore.QRect(162, 50, 91, 20))
        self.txtGarSer.setText(_fromUtf8(""))
        self.txtGarSer.setMaxLength(15)
        self.txtGarSer.setObjectName(_fromUtf8("txtGarSer"))
        self.chkGarSer = QtGui.QCheckBox(self.gbGar)
        self.chkGarSer.setGeometry(QtCore.QRect(10, 50, 81, 21))
        self.chkGarSer.setObjectName(_fromUtf8("chkGarSer"))
        self.lblTot_4 = QtGui.QLabel(self.tabLiquidacio)
        self.lblTot_4.setGeometry(QtCore.QRect(20, 20, 81, 21))
        self.lblTot_4.setObjectName(_fromUtf8("lblTot_4"))
        self.tabMain.addTab(self.tabLiquidacio, _fromUtf8(""))
        self.tabProjecte = QtGui.QWidget()
        self.tabProjecte.setObjectName(_fromUtf8("tabProjecte"))
        self.gbProjecte = QtGui.QGroupBox(self.tabProjecte)
        self.gbProjecte.setGeometry(QtCore.QRect(10, 10, 601, 291))
        self.gbProjecte.setObjectName(_fromUtf8("gbProjecte"))
        self.txtVisatNum = QtGui.QLineEdit(self.gbProjecte)
        self.txtVisatNum.setGeometry(QtCore.QRect(140, 150, 91, 20))
        self.txtVisatNum.setText(_fromUtf8(""))
        self.txtVisatNum.setMaxLength(50)
        self.txtVisatNum.setObjectName(_fromUtf8("txtVisatNum"))
        self.lblVis = QtGui.QLabel(self.gbProjecte)
        self.lblVis.setGeometry(QtCore.QRect(10, 150, 121, 21))
        self.lblVis.setObjectName(_fromUtf8("lblVis"))
        self.lblExe = QtGui.QLabel(self.gbProjecte)
        self.lblExe.setGeometry(QtCore.QRect(10, 90, 121, 21))
        self.lblExe.setObjectName(_fromUtf8("lblExe"))
        self.lblRed = QtGui.QLabel(self.gbProjecte)
        self.lblRed.setGeometry(QtCore.QRect(10, 30, 111, 21))
        self.lblRed.setObjectName(_fromUtf8("lblRed"))
        self.txtRedactor = QtGui.QLineEdit(self.gbProjecte)
        self.txtRedactor.setEnabled(False)
        self.txtRedactor.setGeometry(QtCore.QRect(280, 30, 291, 20))
        self.txtRedactor.setText(_fromUtf8(""))
        self.txtRedactor.setMaxLength(250)
        self.txtRedactor.setObjectName(_fromUtf8("txtRedactor"))
        self.lblDir = QtGui.QLabel(self.gbProjecte)
        self.lblDir.setGeometry(QtCore.QRect(10, 60, 101, 21))
        self.lblDir.setObjectName(_fromUtf8("lblDir"))
        self.lblCons = QtGui.QLabel(self.gbProjecte)
        self.lblCons.setGeometry(QtCore.QRect(10, 120, 121, 21))
        self.lblCons.setObjectName(_fromUtf8("lblCons"))
        self.lblDat = QtGui.QLabel(self.gbProjecte)
        self.lblDat.setGeometry(QtCore.QRect(10, 180, 121, 21))
        self.lblDat.setObjectName(_fromUtf8("lblDat"))
        self.txtDirector = QtGui.QLineEdit(self.gbProjecte)
        self.txtDirector.setEnabled(False)
        self.txtDirector.setGeometry(QtCore.QRect(280, 60, 291, 20))
        self.txtDirector.setText(_fromUtf8(""))
        self.txtDirector.setMaxLength(250)
        self.txtDirector.setObjectName(_fromUtf8("txtDirector"))
        self.btnTecnic = QtGui.QPushButton(self.gbProjecte)
        self.btnTecnic.setGeometry(QtCore.QRect(460, 150, 111, 23))
        self.btnTecnic.setObjectName(_fromUtf8("btnTecnic"))
        self.txtConstructor = QtGui.QLineEdit(self.gbProjecte)
        self.txtConstructor.setEnabled(True)
        self.txtConstructor.setGeometry(QtCore.QRect(140, 120, 431, 20))
        self.txtConstructor.setText(_fromUtf8(""))
        self.txtConstructor.setMaxLength(200)
        self.txtConstructor.setObjectName(_fromUtf8("txtConstructor"))
        self.txtExecutor = QtGui.QLineEdit(self.gbProjecte)
        self.txtExecutor.setEnabled(False)
        self.txtExecutor.setGeometry(QtCore.QRect(280, 90, 291, 20))
        self.txtExecutor.setText(_fromUtf8(""))
        self.txtExecutor.setMaxLength(250)
        self.txtExecutor.setObjectName(_fromUtf8("txtExecutor"))
        self.dateVisat = QtGui.QDateEdit(self.gbProjecte)
        self.dateVisat.setGeometry(QtCore.QRect(140, 180, 91, 22))
        self.dateVisat.setDateTime(QtCore.QDateTime(QtCore.QDate(2014, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateVisat.setDate(QtCore.QDate(2014, 1, 1))
        self.dateVisat.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateVisat.setMaximumDate(QtCore.QDate(2099, 12, 31))
        self.dateVisat.setCalendarPopup(True)
        self.dateVisat.setObjectName(_fromUtf8("dateVisat"))
        self.cboRedactor = QtGui.QComboBox(self.gbProjecte)
        self.cboRedactor.setGeometry(QtCore.QRect(140, 30, 131, 22))
        self.cboRedactor.setEditable(True)
        self.cboRedactor.setObjectName(_fromUtf8("cboRedactor"))
        self.cboDirector = QtGui.QComboBox(self.gbProjecte)
        self.cboDirector.setGeometry(QtCore.QRect(140, 60, 131, 22))
        self.cboDirector.setEditable(True)
        self.cboDirector.setObjectName(_fromUtf8("cboDirector"))
        self.cboExecutor = QtGui.QComboBox(self.gbProjecte)
        self.cboExecutor.setGeometry(QtCore.QRect(140, 90, 131, 22))
        self.cboExecutor.setEditable(True)
        self.cboExecutor.setObjectName(_fromUtf8("cboExecutor"))
        self.lblObs = QtGui.QLabel(self.gbProjecte)
        self.lblObs.setGeometry(QtCore.QRect(10, 210, 121, 21))
        self.lblObs.setObjectName(_fromUtf8("lblObs"))
        self.txtObs = QtGui.QTextEdit(self.gbProjecte)
        self.txtObs.setGeometry(QtCore.QRect(140, 210, 301, 71))
        self.txtObs.setObjectName(_fromUtf8("txtObs"))
        self.gbDocumentacio = QtGui.QGroupBox(self.tabProjecte)
        self.gbDocumentacio.setGeometry(QtCore.QRect(10, 310, 601, 80))
        self.gbDocumentacio.setObjectName(_fromUtf8("gbDocumentacio"))
        self.btnDoc = QtGui.QPushButton(self.gbDocumentacio)
        self.btnDoc.setGeometry(QtCore.QRect(460, 20, 111, 23))
        self.btnDoc.setObjectName(_fromUtf8("btnDoc"))
        self.lblDoc = QtGui.QLabel(self.gbDocumentacio)
        self.lblDoc.setGeometry(QtCore.QRect(10, 30, 101, 21))
        self.lblDoc.setObjectName(_fromUtf8("lblDoc"))
        self.txtDoc = QtGui.QTextEdit(self.gbDocumentacio)
        self.txtDoc.setGeometry(QtCore.QRect(140, 20, 301, 51))
        self.txtDoc.setObjectName(_fromUtf8("txtDoc"))
        self.btnOpenDoc = QtGui.QPushButton(self.gbDocumentacio)
        self.btnOpenDoc.setGeometry(QtCore.QRect(460, 50, 111, 23))
        self.btnOpenDoc.setObjectName(_fromUtf8("btnOpenDoc"))
        self.tabMain.addTab(self.tabProjecte, _fromUtf8(""))
        self.tabComunicacio = QtGui.QWidget()
        self.tabComunicacio.setObjectName(_fromUtf8("tabComunicacio"))
        self.tabMain.addTab(self.tabComunicacio, _fromUtf8(""))
        self.lblInfo = QtGui.QLabel(Dialog)
        self.lblInfo.setGeometry(QtCore.QRect(20, 480, 281, 16))
        self.lblInfo.setText(_fromUtf8(""))
        self.lblInfo.setObjectName(_fromUtf8("lblInfo"))
        self.btnSave = QtGui.QPushButton(Dialog)
        self.btnSave.setGeometry(QtCore.QRect(510, 500, 61, 31))
        self.btnSave.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("icons/save.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSave.setIcon(icon)
        self.btnSave.setIconSize(QtCore.QSize(24, 24))
        self.btnSave.setObjectName(_fromUtf8("btnSave"))
        self.btnClose = QtGui.QPushButton(Dialog)
        self.btnClose.setGeometry(QtCore.QRect(580, 500, 61, 31))
        self.btnClose.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("icons/exit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnClose.setIcon(icon1)
        self.btnClose.setIconSize(QtCore.QSize(24, 24))
        self.btnClose.setObjectName(_fromUtf8("btnClose"))
        self.btnRefresh = QtGui.QPushButton(Dialog)
        self.btnRefresh.setGeometry(QtCore.QRect(440, 500, 61, 31))
        self.btnRefresh.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("icons/refresh.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnRefresh.setIcon(icon2)
        self.btnRefresh.setIconSize(QtCore.QSize(24, 24))
        self.btnRefresh.setObjectName(_fromUtf8("btnRefresh"))

        self.retranslateUi(Dialog)
        self.tabMain.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.tabMain, self.txtId)
        Dialog.setTabOrder(self.txtId, self.txtNumExp)
        Dialog.setTabOrder(self.txtNumExp, self.txtNumHab)
        Dialog.setTabOrder(self.txtNumHab, self.cboTipus)
        Dialog.setTabOrder(self.cboTipus, self.dateEntrada)
        Dialog.setTabOrder(self.dateEntrada, self.dateLlicencia)
        Dialog.setTabOrder(self.dateLlicencia, self.rbFisica)
        Dialog.setTabOrder(self.rbFisica, self.rbJuridica)
        Dialog.setTabOrder(self.rbJuridica, self.cboSol)
        Dialog.setTabOrder(self.cboSol, self.cboSolCif)
        Dialog.setTabOrder(self.cboSolCif, self.txtSolDades)
        Dialog.setTabOrder(self.txtSolDades, self.cboRep)
        Dialog.setTabOrder(self.cboRep, self.txtRepDades)
        Dialog.setTabOrder(self.txtRepDades, self.txtNotifAdreca)
        Dialog.setTabOrder(self.txtNotifAdreca, self.btnJuridica)
        Dialog.setTabOrder(self.btnJuridica, self.txtNotifCp)
        Dialog.setTabOrder(self.txtNotifCp, self.txtNotifPoblacio)
        Dialog.setTabOrder(self.txtNotifPoblacio, self.btnFisica)
        Dialog.setTabOrder(self.btnFisica, self.refcat)
        Dialog.setTabOrder(self.refcat, self.txtRefcat20)
        Dialog.setTabOrder(self.txtRefcat20, self.cboEmp)
        Dialog.setTabOrder(self.cboEmp, self.cboRedactor)
        Dialog.setTabOrder(self.cboRedactor, self.txtRedactor)
        Dialog.setTabOrder(self.txtRedactor, self.cboDirector)
        Dialog.setTabOrder(self.cboDirector, self.txtDirector)
        Dialog.setTabOrder(self.txtDirector, self.cboExecutor)
        Dialog.setTabOrder(self.cboExecutor, self.txtExecutor)
        Dialog.setTabOrder(self.txtExecutor, self.txtConstructor)
        Dialog.setTabOrder(self.txtConstructor, self.txtVisatNum)
        Dialog.setTabOrder(self.txtVisatNum, self.btnTecnic)
        Dialog.setTabOrder(self.btnTecnic, self.dateVisat)
        Dialog.setTabOrder(self.dateVisat, self.txtPress)
        Dialog.setTabOrder(self.txtPress, self.chkLiqAj)
        Dialog.setTabOrder(self.chkLiqAj, self.txtLiqAj)
        Dialog.setTabOrder(self.txtLiqAj, self.txtIcio)
        Dialog.setTabOrder(self.txtIcio, self.chkPlaca)
        Dialog.setTabOrder(self.chkPlaca, self.txtPlaca)
        Dialog.setTabOrder(self.txtPlaca, self.chkPlu)
        Dialog.setTabOrder(self.chkPlu, self.txtPlu)
        Dialog.setTabOrder(self.txtPlu, self.chkRes)
        Dialog.setTabOrder(self.chkRes, self.txtRes)
        Dialog.setTabOrder(self.txtRes, self.chkEnd)
        Dialog.setTabOrder(self.chkEnd, self.chkCar)
        Dialog.setTabOrder(self.chkCar, self.txtCarM)
        Dialog.setTabOrder(self.txtCarM, self.chkMov)
        Dialog.setTabOrder(self.chkMov, self.txtMovM)
        Dialog.setTabOrder(self.txtMovM, self.chkFig)
        Dialog.setTabOrder(self.chkFig, self.txtFigM)
        Dialog.setTabOrder(self.txtFigM, self.chkLeg)
        Dialog.setTabOrder(self.chkLeg, self.chkPar)
        Dialog.setTabOrder(self.chkPar, self.txtParM)
        Dialog.setTabOrder(self.txtParM, self.chkPro)
        Dialog.setTabOrder(self.chkPro, self.chkClavUni)
        Dialog.setTabOrder(self.chkClavUni, self.txtClavUni)
        Dialog.setTabOrder(self.txtClavUni, self.chkClavPlu)
        Dialog.setTabOrder(self.chkClavPlu, self.cboClavPlu)
        Dialog.setTabOrder(self.cboClavPlu, self.chkClavMes)
        Dialog.setTabOrder(self.chkClavMes, self.txtClavMes)
        Dialog.setTabOrder(self.txtClavMes, self.btnRefresh)
        Dialog.setTabOrder(self.btnRefresh, self.btnSave)
        Dialog.setTabOrder(self.btnSave, self.btnClose)
        Dialog.setTabOrder(self.btnClose, self.nif_solic_75)
        Dialog.setTabOrder(self.nif_solic_75, self.txtClavTot)
        Dialog.setTabOrder(self.txtClavTot, self.nif_solic_79)
        Dialog.setTabOrder(self.nif_solic_79, self.txtTotalLiq)
        Dialog.setTabOrder(self.txtTotalLiq, self.chkGarRes)
        Dialog.setTabOrder(self.chkGarRes, self.txtGarRes)
        Dialog.setTabOrder(self.txtGarRes, self.chkGarSer)
        Dialog.setTabOrder(self.chkGarSer, self.txtGarSer)
        Dialog.setTabOrder(self.txtGarSer, self.nif_solic_24)
        Dialog.setTabOrder(self.nif_solic_24, self.txtLlicTot)
        Dialog.setTabOrder(self.txtLlicTot, self.txtPar)
        Dialog.setTabOrder(self.txtPar, self.txtPro)
        Dialog.setTabOrder(self.txtPro, self.nif_solic_25)
        Dialog.setTabOrder(self.nif_solic_25, self.nif_solic_36)
        Dialog.setTabOrder(self.nif_solic_36, self.nif_solic_39)
        Dialog.setTabOrder(self.nif_solic_39, self.txtCar)
        Dialog.setTabOrder(self.txtCar, self.txtEnd)
        Dialog.setTabOrder(self.txtEnd, self.txtFig)
        Dialog.setTabOrder(self.txtFig, self.txtLeg)
        Dialog.setTabOrder(self.txtLeg, self.txtMov)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.gb1Expedient.setTitle(_translate("Dialog", "Expedient", None))
        self.lblNumExp.setText(_translate("Dialog", "Núm. Exp:", None))
        self.lblTip.setText(_translate("Dialog", "Tipus d\'Obra:", None))
        self.lblHab.setText(_translate("Dialog", "Habitatges:", None))
        self.lblDataLlicencia.setText(_translate("Dialog", "Data Llicència:", None))
        self.lblDataEntrada.setText(_translate("Dialog", "Data d\'Entrada:", None))
        self.lblId.setText(_translate("Dialog", "Id autoliquidació:", None))
        self.lblDataLiquidacio.setText(_translate("Dialog", "Data Autoliquidació:", None))
        self.lblEntrada.setText(_translate("Dialog", "Reg. entrada:", None))
        self.btnGenExp.setToolTip(_translate("Dialog", "Actualitzar", None))
        self.btnGenExp.setText(_translate("Dialog", "Generar Exp.", None))
        self.gb2Interessat.setTitle(_translate("Dialog", "Interessat", None))
        self.lblSol.setText(_translate("Dialog", "NIF/CIF Sol·licitant:", None))
        self.lblRep.setText(_translate("Dialog", "NIF Representant:", None))
        self.lblAdre.setText(_translate("Dialog", "Adreça notificació:", None))
        self.lblCp.setText(_translate("Dialog", "C.P. i població:", None))
        self.btnJuridica.setText(_translate("Dialog", "Gestió P. Jurídiques", None))
        self.btnFisica.setText(_translate("Dialog", "Gestió P. Físiques", None))
        self.rbFisica.setText(_translate("Dialog", "P. Física", None))
        self.rbJuridica.setText(_translate("Dialog", "P. Jurídica", None))
        self.lblSol_2.setText(_translate("Dialog", "Tipus Sol·licitant:", None))
        self.gb3Emplasament.setTitle(_translate("Dialog", "Emplaçament", None))
        self.lblRefcat20.setText(_translate("Dialog", "Ref. Catastral:", None))
        self.lblEmpl.setText(_translate("Dialog", "Emplaçament:", None))
        self.lblRef_2.setText(_translate("Dialog", "Parcela:", None))
        self.tabMain.setTabText(self.tabMain.indexOf(self.tabDades), _translate("Dialog", "Dades Expedient", None))
        self.gb5.setTitle(_translate("Dialog", "Impost i Taxes per Expedició Documentació", None))
        self.lblIcio.setText(_translate("Dialog", "ICIO", None))
        self.chkPlaca.setText(_translate("Dialog", "Placa", None))
        self.chkBonIcio.setText(_translate("Dialog", "Bonificació ICIO", None))
        self.gbUrb.setTitle(_translate("Dialog", "Taxa Llicències urbanístiques", None))
        self.chkEnd.setText(_translate("Dialog", "Enderrocs", None))
        self.chkMov.setText(_translate("Dialog", "Moviments Terres", None))
        self.chkLeg.setText(_translate("Dialog", "Legalització", None))
        self.chkPar.setText(_translate("Dialog", "Parcel·lació", None))
        self.chkPro.setText(_translate("Dialog", "Pròrroga", None))
        self.chkPlu.setText(_translate("Dialog", "Plurifamiliars", None))
        self.chkRes.setText(_translate("Dialog", "Resta d\'usos", None))
        self.chkFig.setText(_translate("Dialog", "Figures Planejament", None))
        self.chkCar.setText(_translate("Dialog", "Cartells", None))
        self.lblNumExp_86.setText(_translate("Dialog", "<html><head/><body><p>m²</p></body></html>", None))
        self.lblNumExp_97.setText(_translate("Dialog", "<html><head/><body><p>m²</p></body></html>", None))
        self.lblNumExp_98.setText(_translate("Dialog", "<html><head/><body><p>m²</p></body></html>", None))
        self.lblNumExp_99.setText(_translate("Dialog", "<html><head/><body><p>m³</p></body></html>", None))
        self.lblTot_2.setText(_translate("Dialog", "Total Llicències Urbanístiques:", None))
        self.chkBonLlic.setText(_translate("Dialog", "Bonificació Llicències Urbanístiques", None))
        self.gbClav.setTitle(_translate("Dialog", "Taxa de Clavegueram", None))
        self.chkClavUni.setText(_translate("Dialog", "Unifamiliar", None))
        self.chkClavPlu.setText(_translate("Dialog", "Plurifamiliars", None))
        self.chkClavMes.setText(_translate("Dialog", "Plurifamiliar >13", None))
        self.lblNumExp_79.setText(_translate("Dialog", "Taxa de Clavegueram:", None))
        self.lblTot_3.setText(_translate("Dialog", "Total Clavegueram:", None))
        self.lblNumExp_82.setText(_translate("Dialog", "Total Clavegueram", None))
        self.gbTot.setTitle(_translate("Dialog", "Total Impost i Taxes", None))
        self.lblNumExp_84.setText(_translate("Dialog", "Taxa de Clavegueram:", None))
        self.lblNumExp_87.setText(_translate("Dialog", "Total Clavegueram", None))
        self.lblTotLiq.setText(_translate("Dialog", "Autoliquidació:", None))
        self.lblTotLiq_2.setText(_translate("Dialog", "Liquidació:", None))
        self.chkLiqAj.setText(_translate("Dialog", "Liquidacio aj.:", None))
        self.gbGar.setTitle(_translate("Dialog", "Garanties", None))
        self.chkGarRes.setText(_translate("Dialog", "Residus", None))
        self.chkGarSer.setText(_translate("Dialog", "Serveis", None))
        self.lblTot_4.setText(_translate("Dialog", "Pressupost:", None))
        self.tabMain.setTabText(self.tabMain.indexOf(self.tabLiquidacio), _translate("Dialog", "Liquidació", None))
        self.gbProjecte.setTitle(_translate("Dialog", "Projecte", None))
        self.lblVis.setText(_translate("Dialog", "Num. Visat:", None))
        self.lblExe.setText(_translate("Dialog", "Director execució d\'Obra:", None))
        self.lblRed.setText(_translate("Dialog", "Redactor del Projecte:", None))
        self.lblDir.setText(_translate("Dialog", "Director d\'Obra:", None))
        self.lblCons.setText(_translate("Dialog", "Constructor:", None))
        self.lblDat.setText(_translate("Dialog", "Data Visat:", None))
        self.btnTecnic.setText(_translate("Dialog", "Gestió Tècnics", None))
        self.lblObs.setText(_translate("Dialog", "Observacions:", None))
        self.gbDocumentacio.setTitle(_translate("Dialog", "Documentació", None))
        self.btnDoc.setText(_translate("Dialog", "Adjuntar Document", None))
        self.lblDoc.setText(_translate("Dialog", "Ruta documentació:", None))
        self.btnOpenDoc.setText(_translate("Dialog", "Veure Document", None))
        self.tabMain.setTabText(self.tabMain.indexOf(self.tabProjecte), _translate("Dialog", "Projecte", None))
        self.tabMain.setTabText(self.tabMain.indexOf(self.tabComunicacio), _translate("Dialog", "Comunicació i Esmenes", None))
        self.btnSave.setToolTip(_translate("Dialog", "Desar", None))
        self.btnClose.setToolTip(_translate("Dialog", "Sortir", None))
        self.btnRefresh.setToolTip(_translate("Dialog", "Actualitzar", None))

